---
downloads: ~/.ansible-downloads/
user: ajackson
gitfolder: "/Users/{{ user }}/Git"

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/lordmuffin/dotfiles.git
dotfiles_repo_username: lordmuffin
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ gitfolder }}/dotfiles"
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_repo: https://github.com/Homebrew/brew

homebrew_installed_packages:
  - autoconf
  - aws-elasticbeanstalk
  - awscli
  - bash-completion
  - cscope
  - ctags
  - doxygen
  - gettext
  - ghi
  - gifsicle
  - git
  - gmp
  - gnu-tar
  - gnupg
  - gnutls
  - go
  - gpg
  - hub
  - httpie
  - icu4c
  - iperf
  - libassuan
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libksba
  - libtasn1
  - libunistring
  - libusb
  - libyaml
  - lua
  - macvim
  - mcrypt
  - mhash
  - ncurses
  - nettle
  - nmap
  - node
  - npth
  - nvm
  - openssl
  - p11-kit
  - packer
  - pcre
  - pcre2
  - pinentry
  - pinentry-mac
  - powerlevel9k
  - pv
  - python
  - python@2
  - readline
  - reattach-to-user-namespace
  - sqlite
  - ssh-copy-id
  - the_silver_searcher
  - thefuck
  - tmux
  - unbound
  - wget
  - xz
  - zsh
homebrew_upgrade_all_packages: yes
homebrew_taps:
  - caskroom/cask
  - homebrew/core
homebrew_cask_apps:
  - 1password
  - atom
  - chromedriver
  - docker
  - dropbox
  - firefox
  - font-hack-nerd-font
  - google-chrome
  - handbrake
  - iterm2
  - licecap
  - macvim
  - monolingual
  - nvalt
  - powershell
  - sequel-pro
  - skitch
  - slack
  - transmit
  - vagrant
  - virtualbox
  - visual-studio-code
homebrew_cask_appdir: /Applications

applications:
  - monolingual


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: /Users/vagrant/Git/dotfiles/.osx

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  - name: pexpect
    state: present # present/absent/latest, default: present
    #version: "4.2.1" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
