---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: yes

# Update from /usr/local/etc/ansible - Old Version?
# - name: Symlink /usr/local/bin/ansible to /etc/ansible.
#   file:
#     src: /etc/ansible
#     path: /usr/local/bin/ansible
#     state: link
