---
# TODO: Use sudo once .osx can be run via root with no user interaction.
# - name: Install System Settings
#   shell: "{{ osx_script }}"
#   changed_when: false
#   become: true

- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

# - name: Install Homebrew
#   shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
#   when: brew_installed.stat.exists == false

- homebrew:
    name: "{{items}}"
    state: present
    # install_options: with-baz,enable-debug
    update_homebrew: yes
    update_all: yes
    with_items: "{{homebrew_install_apps}}"

- homebrew_cask:
    name: "{{items}}"
    state: present
    with_items: "{{homebrew_cask_apps}}"

- homebrew_tap:
    name: "{{items}}"
    state: present
    with_items: "{{homebrew_taps}}"



# - name: Instal required Homebrew Taps
#   shell: brew tap {{ item }}
#   with_items: "{{brew_taps}}"
# - name: Check homebrew-cask is installed
#   stat: path=/usr/local/bin/brew-cask.rb
#   register: brew_cask_installed
# - name: Install homebrew-cask
#   shell: brew tap caskroom/cask
#   when: brew_cask_installed.stat.exists == false

    ### UTILS

# - name: Install libraries/utils with homebrew
#   homebrew: name={{ item }} state=present
#   with_items: "{{applications}}"

- name: Cleanup after brewing
  shell: brew cleanup
