---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Install homebrew applications
  shell: "{{ osx_script }}"
  changed_when: false

- homebrew:
    name: "{{items}}"
    state: present
    # install_options: with-baz,enable-debug
    update_homebrew: yes
    update_all: yes
    with_items: "{{homebrew_installed_packages}}"

- homebrew_cask:
    name: "{{items}}"
    state: present
    with_items: "{{homebrew_cask_apps}}"

- homebrew_taps:
    name: "{{itmes}}"
    state: present
    with_items: "{{homebrew_taps}}"
