---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: set .osx executable
  file:
    state: touch
    path: "{{ osx_script }}"
    mode: "a+x"
- name: script set perms.
  shell: "chmod +x /Users/vagrant/Git/dotfiles/.osx"
  changed_when: false
- name: Run .osx dotfiles.
  shell: "{{ osx_script }}"
  changed_when: false
