---
- name: Install software
  package: name={{ item }} state=present
  with_items:
    - zsh

    ### APPZ

# - name: Check for installed apps(casks)
#   shell: brew cask list | grep {{ item }}
#   register: installed_applications
#   with_items: "{{applications}}"
#   ignore_errors: true
#
# - name: Install Apps with brew-cask
#   shell: brew cask install {{ item }}
#   with_items: "{{applications}}"
#   when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

# Caveats: megasync only works if called from /Applications
- name: Linking MEGASync with brew-cask
  shell: ln -s '/opt/homebrew-cask/Caskroom/megasync/latest/MEGAsync.app' '/Applications/MEGAsync.app'
  when: "'megasync' in applications"
  ignore_errors: true # hacky


### ZSH radness

# - name: Set zsh shell
#   shell: 'chsh -s $(which zsh)'

# - name: Get current Terminal profile.
#   shell: defaults read com.apple.Terminal 'Default Window Settings'
#   register: terminal_theme
#   changed_when: false
#
# - name: Ensure custom Terminal profile is added.
#   shell: open files/Solarized-Dark.terminal
#   changed_when: false
#   when: "'Solarized-Dark' not in terminal_theme.stdout"
#
# - name: Ensure custom Terminal profile is set as default.
#   shell: "{{ item }}"
#   with_items:
#     - defaults write com.apple.Terminal 'Default Window Settings' -string 'Solarized-Dark'
#     - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Solarized-Dark'
#   changed_when: false
#   when: "'Solarized Dark ansi' not in terminal_theme.stdout"
#
- name: Use GNU tools instead of osx counterparts (grep find etc)
  shell: echo 'export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH' >> ~/.zshrc


- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  sudo: false
  tags: install_oh_my_zsh


### OSX SETTINGS
- name: Configure System Settings
  script: scripts/system_settings.sh
  sudo: true



### DOTFILES

- name: Check rcm is installed
  stat: path=/usr/local/bin/rcup
  register: rcm_installed

- name: Install rcm for dotfiles management
  shell: brew tap thoughtbot/formulae && brew install rcm
  when: rcm_installed.stat.exists == false

- name: Check ~/src dir exists
  stat: path=~/src/
  register: src_dir_exists

- name: Assures ~/src dir exists
  file: path=~/src state=directory

- name: Assures ~/src/thoughtbot dir exists
  file: path=~/src/thoughtbot state=directory

- name: Install thoughtbot/dotfiles
  git: repo=https://github.com/thoughtbot/dotfiles.git dest=~/src/thoughtbot/dotfiles

- name: Link ~/dotfiles to ~/src/thoughtbot/dotfiles
  file: dest=~/dotfiles
        src=~/src/thoughtbot/dotfiles
        state=link
        force=yes

- name: Assures ~/src/{{ dotfiles_repo_username }} dir exists
  file: path=~/src/{{ dotfiles_repo_username }} state=directory

- name: Install {{ dotfiles_repo_username }}/dotfiles
  git: repo=https://github.com/{{ dotfiles_repo_username }}/dotfiles.git dest=~/src/{{ dotfiles_repo_username }}/dotfiles

- name: Link ~/dotfiles-local to ~/src/{{ dotfiles_repo_username }}/dotfiles
  file: dest=~/dotfiles-local
        src=~/src/{{ dotfiles_repo_username }}/dotfiles
        state=link
        force=yes

- name: Generate dotfiles with rcup
  shell: rcup -B 0 -f -g -d ~/dotfiles -K > ~/dotfiles/rcup.sh

- name: Assures rcup.sh is executable
  file:
    path: ~/dotfiles/rcup.sh
    state: touch
    mode: u=rwX,g=rX,o=rX
# This says yes to all the script responses.
- name: Run rcup dotfiles setup
  shell: |

    spawn sh ~/dotfiles/rcup.sh

    expect "\r\n"
    send "Y\n"

  args:
    executable: /usr/bin/expect

- name: Add zsh to list of allowed shells
  lineinfile: dest=/etc/shells line=/usr/local/bin/zsh state=present owner=root group=wheel mode=0644
  become: yes

- name: Register currently configured login shell (https://github.com/hnakamur/ansible-role-osx-login-shell/blob/master/tasks/main.yml)
  shell: dscl . read ~ UserShell | awk '{print $2}'
  register: osx_login_shell_current_login_shell
  changed_when: false

- name: Set zsh as login shell
  command: chsh -s /usr/local/bin/zsh
  when: osx_login_shell_current_login_shell.stdout != "/usr/local/bin/zsh"

## POST INSTALL STEPS / Cask gotchas
#
# require manual intervention!
#

- name: Run Monolingual
  shell: open ~/Applications/Monolingual.app
  when: "'monolingual' in applications"
