---
# Custom Terminal theme.
- name: Git Prezto repo
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto

- name: Install zprezto
  command: |
    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
  changed_when: false

# Still need to import my prezto files. - just copy dotfiles - need font crap.
